---
title: "Plotly Choropleth"
author: "John Little"
date: "`r Sys.Date()`"
output: html_notebook
---

## Load Libraries

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(plotly)
library(crosstalk)
library(leaflet)
library(gganimate)
```



## Get Census Data

```{r}
nc_2016 <- 
  get_acs(geography = "county",
          variables = "B01003_001",
          state = "NC",
          geometry = TRUE) %>% 
  mutate(year = "2016")

nc_2015 <- 
  get_acs(geography = "county",
          variables = "B01003_001",
          state = "NC",
          year = 2015,
          geometry = TRUE) %>% 
  mutate(year = "2015")

nc_2014 <- 
  get_acs(geography = "county",
          variables = "B01003_001",
          state = "NC",
          year = 2014,
          geometry = TRUE) %>% 
  mutate(year = "2014")

nc_2013 <- 
  get_acs(geography = "county",
          variables = "B01003_001",
          state = "NC",
          year = 2013,
          geometry = TRUE) %>% 
  mutate(year = "2013")
```

## Bind Rows

```{r}
big_table <- rbind(nc_2016, nc_2015, nc_2014, nc_2013) 
glimpse(big_table)

big_table2 <- big_table
st_geometry(big_table2) <- NULL
```


## Test

first:  ggplot facet_wrap

```{r}
ggplot(big_table) +
  geom_sf(aes(fill = estimate, color = estimate)) +
  facet_wrap(~ year)
```


Second:  side by side bargraph

```{r}
big_table2 %>% 
  mutate(county = str_extract(NAME, "\\w+")) %>% 
  filter(county == "Mecklenburg" | 
           county == "Durham" | 
           county == "Guilford") %>% 
  select(county, estimate, year) %>% 
  gather("foo", "year", -county, -estimate) %>% 
  ggplot() +
  geom_col(aes(x = county, y = estimate, fill = year), 
           position = "dodge") +
  scale_fill_viridis_d() +
  coord_flip() 
```

Third:  Simple ggplotly for one year (2016) but no slider.

```{r}
ggnc <- ggplot(nc_2016) +
  geom_sf(aes(fill = estimate, color = estimate)) 

ggplotly(ggnc)


```

fourth:  crosstalk shared data & slider

```{r}
shared_bigtable <- SharedData$new(big_table %>% 
  mutate(year = as.numeric(year)))
```

```{r}
nc_share_slide <- filter_slider("mapyear", "YEAR", shared_bigtable, 
              column=~year, timeFormat = "%Y")
```


```{r}
GreenPalette <- colorNumeric(palette = "Greens",
                               domain = big_table$estimate)

big_table %>% 
  st_transform(crs = "+init=epsg:4326") %>%
  leaflet(width = "100%") %>%
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addPolygons(fillOpacity = 0.7,
              smoothFactor = 0,
              stroke = FALSE, 
              color = ~GreenPalette(estimate))
```


```{r}
GreenPalette <- colorNumeric(palette = "Greens",
                               domain = big_table$estimate)

nc_share_leaf <- (shared_bigtable %>% 
  #st_transform(crs = "+init=epsg:4326") %>%
  leaflet(width = "100%") %>%
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addPolygons(fillOpacity = 0.7,
              smoothFactor = 0,
              stroke = FALSE, 
              color = ~GreenPalette(estimate)))
```


```{r}
bscols(nc_share_slide, nc_share_leaf)
```

Fifth:  annimate with gganimate

```{r}
big3 <- big_table %>% mutate(year = as.numeric(year))

big3p <- ggplot() +
  geom_sf(data = big3 %>% filter(year == 2016), 
          aes(fill = estimate, color = estimate)) +
  geom_sf(data = big3 %>% filter(year == 2013),
          aes(fill = estimate, color = estimate)) +
  coord_sf(crs = 4269, datum = NA) +
  scale_fill_viridis_c() +
  scale_color_viridis_c() +
  view_zoom_manual(1, 1, xmin = views$xmin, xmax = views$xmax, 
                   ymin = views$ymin, ymax = views$ymax, wrap = TRUE)
  # facet_wrap(~ year) +
  #  labs(title = 'Year: {frame_time}') +
  #transition_time(year) +
  #ease_aes('linear')

big3p

animate(big3p, 100, 10)
```


```{r}
earth <- sf::st_as_sf(rnaturalearth::countries110)
views <- data.frame(rbind(
  st_bbox(earth[earth$name == 'Denmark',]),
  st_bbox(earth[earth$name == 'Australia',])
))
p <- ggplot() + 
  geom_sf(data = earth, fill = 'white') + 
  geom_sf(data = earth[earth$name %in% c('Denmark', 'Australia'),], fill = 'forestgreen') + 
  theme(panel.background = element_rect('lightblue')) + 
  view_zoom_manual(1, 1, xmin = views$xmin, xmax = views$xmax, ymin = views$ymin, ymax = views$ymax, wrap = TRUE)
animate(p, 100, 10)
```




```{r}
plot_13 <- ggplot(nc_2013) +
  geom_sf(aes(fill = estimate, color = estimate)) 

plot_14 <- ggplot(nc_2014) +
  geom_sf(aes(fill = estimate, color = estimate)) 

plot_15 <- ggplot(nc_2015) +
  geom_sf(aes(fill = estimate, color = estimate)) 

plot_16 <- ggplot(nc_2016) +
  geom_sf(aes(fill = estimate, color = estimate)) 

plot_13
```



Sixth:  foo

```{r}

ggnc <- ggplot() +
  geom_sf(data = nc_2016, 
          aes(fill = estimate, color = estimate)) +
  geom_sf(data = nc_2013, 
          aes(fill = estimate, color = estimate)) 

ggnc




ggpp <- ggplotly(ggnc) %>% 
  add_trace(
    z = ~estimate,
    frame = ~year)

ggpp

animation_slider(ggpp)
```



```{r}
ggplotly(ggnc, tooltip = "NAME") %>% 
  layout(
    hovermode = "x",
    margin = list(
      t = 20,
      b = 20,
      l = 20,
      r = 20),
  )
```







## County Level Plotly 

https://moderndata.plot.ly/county-level-choropleth-in-plotly-and-r/

```{r}
county_df <- map_data("county") 
nc_county <- county_df %>% filter(region == "north carolina")

  
state_df <- map_data("state") 
nc_df <- state_df %>% filter(region == "north carolina")


```


## Make Plotly Map

```{r}
boarder_white <- list(color = toRGB("white"), width = 2)

usa_projection <- list(scope = "usa", 
                       projection = list(type = "albers usa"),
                       showlakes = TRUE,
                       lakecolor = toRGB("white"))

plotlymap <- plot_geo(big_table, locationmode = 'county names') %>% 
  add_trace(
    z = ~estimate, text = ~estimate, location = ~NAME,
    color = ~estimate, colors = "Purples",
    frame = ~NAME
  ) %>% 
  layout = usa_projection

plotlymap
```


```{r}
ggplotly()
```



